version: '3.4'

services:
  php:
    build:
      context: docker/php
    depends_on:
      - db
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app:rw,cached

  db:
    image: mysql:8.0.21
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shop
      - MYSQL_USER=shop
      - MYSQL_PASSWORD=shop
    ports:
      - ${MYSQL_PORT:-3306}:3306
    volumes:
      - db-data:/var/lib/mysq:rw

volumes:
  db-data: {}
